# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photo_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PIL import Image, ImageFilter


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.picture_file = "Lelouch.jpg"
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 600, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 521))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.picture = QtWidgets.QLabel(self.tab_2)
        self.picture.setGeometry(QtCore.QRect(0, 12, 600, 501))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap(self.picture_file))
        self.picture.setObjectName("picture")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_blur = QtWidgets.QLabel(self.tab_3)
        self.label_blur.setGeometry(QtCore.QRect(150, 0, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_blur.setFont(font)
        self.label_blur.setStyleSheet("background-color: rgb(80, 133, 255);")
        self.label_blur.setAlignment(QtCore.Qt.AlignCenter)
        self.label_blur.setWordWrap(False)
        self.label_blur.setIndent(10)
        self.label_blur.setObjectName("label_blur")
        self.slider_blur = QtWidgets.QSlider(self.tab_3)
        self.slider_blur.setGeometry(QtCore.QRect(150, 50, 300, 30))
        self.slider_blur.setStyleSheet("")
        self.slider_blur.setOrientation(QtCore.Qt.Horizontal)
        self.slider_blur.setObjectName("slider_blur")
        self.slider_blur.setMinimum(0)
        self.slider_blur.setMaximum(100)
        self.label_sharp = QtWidgets.QLabel(self.tab_3)
        self.label_sharp.setGeometry(QtCore.QRect(150, 160, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_sharp.setFont(font)
        self.label_sharp.setStyleSheet("background-color: rgb(57, 0, 86);\n"
"color: rgb(193, 255, 134);")
        self.label_sharp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sharp.setWordWrap(False)
        self.label_sharp.setIndent(10)
        self.label_sharp.setObjectName("label_sharp")
        self.slider_sharp = QtWidgets.QSlider(self.tab_3)
        self.slider_sharp.setGeometry(QtCore.QRect(150, 210, 300, 30))
        self.slider_sharp.setStyleSheet("")
        self.slider_sharp.setOrientation(QtCore.Qt.Horizontal)
        self.slider_sharp.setObjectName("slider_sharp")
        self.slider_sharp.setMinimum(0)
        self.slider_sharp.setMaximum(100)
        self.label_median = QtWidgets.QLabel(self.tab_3)
        self.label_median.setGeometry(QtCore.QRect(150, 320, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_median.setFont(font)
        self.label_median.setStyleSheet("background-color: rgb(58, 194, 130);\n"
"")
        self.label_median.setAlignment(QtCore.Qt.AlignCenter)
        self.label_median.setWordWrap(False)
        self.label_median.setIndent(10)
        self.label_median.setObjectName("label_median")
        self.slider_median = QtWidgets.QSlider(self.tab_3)
        self.slider_median.setGeometry(QtCore.QRect(150, 370, 300, 30))
        self.slider_median.setStyleSheet("")
        self.slider_median.setOrientation(QtCore.Qt.Horizontal)
        self.slider_median.setObjectName("slider_median")
        self.slider_median.setMinimum(1)
        self.slider_median.setMaximum(3)
        self.tabWidget.addTab(self.tab_3, "")

        self.button_apply = QtWidgets.QPushButton(self.tab_3)
        self.button_apply.setText("Apply")
        self.button_apply.setFixedSize(100, 60)
        self.button_apply.move(250, 400)
        self.button_apply.clicked.connect(self.image_tab_click_event)


        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Image"))
        self.label_blur.setText(_translate("MainWindow", "Blur"))
        self.label_sharp.setText(_translate("MainWindow", "Sharp"))
        self.label_median.setText(_translate("MainWindow", "Median"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Form"))

    def image_tab_click_event(self):
        try:
            orig = Image.open(self.picture_file)
            orig.load()
            print(self.slider_blur.value(), self.slider_sharp.value(), self.slider_median.value())
            blur = orig.filter(ImageFilter.GaussianBlur(radius=int(self.slider_blur.value())))
            sharp = blur.filter(ImageFilter.UnsharpMask(radius=int(self.slider_sharp.value())))
            median = sharp.filter(ImageFilter.MedianFilter(size=int(self.slider_median.value())))

            median.save(self.picture_file)
            self.picture.setPixmap(QtGui.QPixmap(self.picture_file))
        except Exception as error:
            print(error)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
